Lab3
rita-mazets/MyCalendarSite pull request #2
Opened 2022-04-15 17:54 UTC by rita-mazets

2022-04-22 08:01 UTC, Nastik1811 requested changes
Looks good but needs some work on the html

2022-04-22 08:01 UTC, nastik1811 commented on lab3/index.html
> +							<a href="#accesmant"><button type="button"class="colendar-button colendar-button-active"></button></a>
It's invalid html. You can't place interactive elements inside a link. You can style `a` itself however you like, no need in button element

2022-04-22 08:01 UTC, nastik1811 commented on lab3/index.html
> +							<a href="#accesmant"><button type="button"class="colendar-button colendar-button-active"></button></a>
Also, you probably have a typo in the href  :)

2022-04-22 08:01 UTC, nastik1811 commented on lab3/index.html
> +				<button type="submit" class="custom-button accesmant-button" style="margin-top: 5%;">Add pictures</button>
i guess it's `input type="file"`

2022-04-22 08:01 UTC, nastik1811 commented on lab3/index.html
> +		<div class="accesmant article_container">
As a user use these fields to submit some information about a week, it should be a `form`

2022-04-22 08:01 UTC, nastik1811 commented on lab3/index.html
> +				<a name="accesmant"></a>
What is the goal of `a` here?

2022-04-22 08:01 UTC, nastik1811 commented on lab3/index.html
> +				<span>How do you rate this week?</span>
Looks more like a heading

2022-04-22 08:01 UTC, nastik1811 commented on lab3/index.html
> +				<span >Here you can describe your week</span>
Also a heading

2022-04-22 08:01 UTC, nastik1811 commented on lab3/index.html
> +			</div>
`nav` is usually used for main app navigation

2022-04-22 08:01 UTC, nastik1811 commented on lab3/logIn.html
> +								<label class="form-input-label">Password</label>
labels should have `for` attribute

2022-04-22 08:01 UTC, nastik1811 commented on lab3/logIn.html
> +							<span><a href="signUp.html" class="sign-mini-text">I don't have an account</a></span>
no need of wrapping it into `span`

2022-04-22 08:01 UTC, nastik1811 commented on lab3/signUp.html
> +                                <div  class="form-block-select" style="width: 30%; float:right;">
inline styles is evil 🙈

2022-04-26 23:28 UTC, rita-mazets commented on lab3/index.html
> +				<a name="accesmant"></a>
It is anchor.

2022-04-27 16:48 UTC, Nastik1811 commented
Why did you close this one?

2022-04-27 17:59 UTC, rita-mazets commented
I fixed the bugs and opened a new one.

  
>Среда, 27 апреля 2022, 19:48 +03:00 от Anastasia Lugovskaya ***@***.***>:
> 
> 
>Why did you close this one?
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you modified the open/close state. Message ID:  <rita-mazets/MyCalendarSite/pull/2/c1111227553 @ github . com> 
 
 
С уважением,
Маргарита Мазец
***@***.***
 

2022-04-28 07:39 UTC, Nastik1811 commented
There is no need to open a new PR when you've fixed something. You're just pushing changes to the same branch (PR will be updated automatically) and then re-request the review

2022-04-28 07:43 UTC, Nastik1811 commented
If I'm not mistaken you still can re-open this PR, so we could continue discussion here 

P.S. it makes more sense, as I can see comments I left here and which one you have fixed or explained

2022-04-28 07:47 UTC, Nastik1811 commented
And GitHub even gives me what comments are fixed.🙂 
<img width="796" alt="Screenshot 2022-04-28 at 10 44 12" src="https://user-images.githubusercontent.com/37243282/165703055-40953a19-1b5b-44ef-9fd4-61dceb147b85.png">

2022-04-28 08:02 UTC, rita-mazets commented
I am sorry for the inconvenience, I opened everything.

2022-04-28 09:08 UTC, nastik1811 approved these changes
No worries )

For this work you get `9` as well

2022-05-18 20:00 UTC, merged