added lab4
rita-mazets/MyCalendarSite pull request #4
Opened 2022-05-18 20:25 UTC by rita-mazets

2022-05-20 10:17 UTC, Nastik1811 requested changes

2022-05-20 10:17 UTC, Nastik1811 commented on lab4/frontend/static/js/components/Assessment.js
> +    if(data === '' || data === null || data === undefined || data === "null")
`if (!data)` будет также работать

2022-05-20 10:17 UTC, Nastik1811 commented on lab4/frontend/static/js/elements.js
> +    var signOutA = document.createElement('a')
`var` мы не используем

2022-05-20 10:17 UTC, Nastik1811 commented on lab4/frontend/static/js/storage.js
> +    xhr.send();
https://learn.javascript.ru/fetch

2022-05-23 14:45 UTC, rita-mazets commented on lab4/frontend/static/js/components/Assessment.js
> +    if(data === '' || data === null || data === undefined || data === "null")
Все-таки логика предусматривает проверку if(data !== "null"). Убрала лишние проверки

2022-05-23 14:46 UTC, rita-mazets commented on lab4/frontend/static/js/elements.js
> +    var signOutA = document.createElement('a')
исправила!)

2022-05-23 14:47 UTC, rita-mazets commented on lab4/frontend/static/js/storage.js
> +    xhr.send();
Тут метод   getDownloadURL() уже сделал всю нужную работу, а написание этого кода было лишним.

2022-05-23 15:02 UTC, rita-mazets commented
Исправила ошибки

2022-05-25 12:37 UTC, nastik1811 approved these changes

2022-05-26 09:07 UTC, rita-mazets commented
Added js

2022-05-26 09:07 UTC, merged